dataset_path: ./data/processed/amass
graph_config: ./config/amass_skeleton.yaml
output_path: ./output/amass
num_workers: 0

num_epochs: 50
history_length: 40
prediction_horizon: 20

eval_frequency: 1000
num_iteration_eval: 20
batch_size_eval: 50


lr: 1.e-3
clip_grad_norm: 1.
batch_size: 128
encoder_hidden_size: 128
bottleneck_size: 128
decoder_hidden_size: 128
output_size: 128
latent_size: 5
enc_num_layers: 1
dec_num_layers: 1
dropout: 0.0

random_prediction_horizon: True
curriculum_it: 0

datasets_train:
  - ACCAD
  - EKUT
  - MPImosh
  - TotalCapture
  - BMLhandball
  - DFaust67
  - EyesJapanDataset
  - MPILimits
  - SFU
  - TCDhandMocap
  - CMU
  - KIT
  - BMLmovi
  - MPIHDM05
  - BMLrub
  - HumanEva
datasets_test:
  - Transitionsmocap
  - SSMsynced