dataset_path: ./data/processed/h3.6m.npz
graph_config: ./config/h36m_skeleton_gen.yaml
dataset_fps: 50
dataset_downsample_factor: 1
output_path: ./output/h36m
num_workers: 5

num_epochs: 10
history_length: 25
prediction_horizon_train: 100
prediction_horizon_eval: 100
prediction_horizon: 100

eval_frequency: 1000
num_iteration_eval: 20
batch_size_eval: 100


lr: 1.e-3
clip_grad_norm: 1.
batch_size: 32
encoder_hidden_size: 96
bottleneck_size: 96
decoder_hidden_size: 96
output_size: 128
latent_size: 5
enc_num_layers: 1
dec_num_layers: 1
dropout: 0.0

random_prediction_horizon: True
curriculum_it: 10000

subjects_train:
  - S1
  - S6
  - S7
  - S8
  - S5
subjects_eval:
  - S11
  - S9
subjects_test:
  - S11
  - S9

test_actions:
  - walking
  - eating
  - smoking
  - discussion
  - directions
  - greeting
  - phoning
  - posing
  - purchases
  - sitting
  - sittingdown
  - takingphoto
  - waiting
  - walkingdog
  - walkingtogether