offsets:
# 1
  - - 0
    - 0
    - 0
 # 2
  - - -132.948591
    - 0
    - 0
# 3
  - - 0
    - -442.894612
    - 0
# 4
  - - 0
    - -454.206447
    - 0
# 5
  - - 0
    - 0
    - 162.767078
# 6
  - - 0
    - 0
    - 74.999437
# 7
  - - 132.948826
    - 0
    - 0
# 8
  - - 0
    - -442.894413
    - 0
# 9
  - - 0
    - -454.20659
    - 0
# 10
  - - 0
    - 0
    - 162.767426
# 11
  - - 0
    - 0
    - 74.999948
# 12
  - - 0
    - 0.1
    - 0
# 13
  - - 0
    - 233.383263
    - 0
# 14
  - - 0
    - 257.077681
    - 0
# 15
  - - 0
    - 121.134938
    - 0
# 16
  - - 0
    - 115.002227
    - 0
# 17
  - - 0
    - 257.077681
    - 0
# 18
  - - 0
    - 151.034226
    - 0
# 19
  - - 0
    - 278.882773
    - 0
# 20
  - - 0
    - 251.733451
    - 0
# 21
  - - 0
    - 0
    - 0
# 22
  - - 0
    - 0
    - 99.999627
# 23
  - - 0
    - 100.000188
    - 0
# 24
  - - 0
    - 0
    - 0
# 25
  - - 0
    - 257.077681
    - 0
# 26
  - - 0
    - 151.031437
    - 0
# 27
  - - 0
    - 278.892924
    - 0
# 28
  - - 0
    - 251.72868
    - 0
# 29
  - - 0
    - 0
    - 0
# 30
  - - 0
    - 0
    - 99.999888
# 31
  - - 0
    - 137.499922
    - 0
# 32
  - - 0
    - 0
    - 0

parents:
  - -1
  - 0
  - 1
  - 2
  - 3
  - 4
  - 0
  - 6
  - 7
  - 8
  - 9
  - 0
  - 11
  - 12
  - 13
  - 14
  - 12
  - 16
  - 17
  - 18
  - 19
  - 20
  - 19
  - 22
  - 12
  - 24
  - 25
  - 26
  - 27
  - 28
  - 27
  - 30

joints_left:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31

joints_right:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23

joints_static:
  - 0
  - 5
  - 10
  - 15
  - 20
  - 21
  - 22
  - 23
  - 28
  - 29
  - 30
  - 31

joints_type:
  - Hips # 0
  - RightUpLeg # 1
  - RightLeg # 2
  - RightFoot # 3
  - RightToeBase # 4
  - Site # 5
  - LeftUpLeg # 6
  - LeftLeg # 7
  - LeftFoot # 8
  - LeftToeBase # 9
  - Site # 10
  - Spine # 11
  - Spine1 # 12
  - Neck # 13
  - Head # 14
  - Site # 15
  - LeftShoulder # 16
  - LeftArm # 17
  - LeftForeArm # 18
  - LeftHand # 19
  - LeftHandThumb # 20
  - Site # 21
  - LeftWristEnd # 22
  - Site # 23
  - RightShoulder # 24
  - RightArm # 25
  - RightForeArm # 26
  - RightHand # 27
  - RightHandThumb # 28
  - Site # 29
  - RightWristEnd # 30
  - Site # 31