dataset_path: ./data/processed/nuitrack
graph_config: ./config/nuitrack_skeleton.yaml
output_path: ./output/nuitrack
num_workers: 0

num_epochs: 10
history_length: 30
prediction_horizon: 15

eval_frequency: 1000
num_iteration_eval: 20
batch_size_eval: 50

ignore_absolute_root_rotation: True


lr: 1.e-3
clip_grad_norm: 1.
batch_size: 128
encoder_hidden_size: 128
bottleneck_size: 128
decoder_hidden_size: 128
output_size: 128
latent_size: 3
enc_num_layers: 1
dec_num_layers: 1
dropout: 0.0
node_dropout: 0.0

datasets_train:
  - ACCAD
  - EKUT
  - MPImosh
  - TotalCapture
  - BMLhandball
  - DFaust67
  - EyesJapanDataset
  - MPILimits
  - SFU
  - TCDhandMocap
  - CMU
  - KIT
  - BMLmovi
  - BMLrub
  - HumanEva
  - Transitionsmocap
  - SSMsynced

datasets_test:
  - MPIHDM05